Create TensorBoard.sh
c3se/alvis-intro pull request #12
Opened 2024-11-21 12:38 UTC by saharmahdie

2024-11-22 07:52 UTC, VRehnberg commented on tutorial/5_profiling/TensorBoard.sh
> +
```suggestion
```
this part is only needed in sbatch jobscripts

2024-11-22 07:52 UTC, VRehnberg commented on tutorial/5_profiling/TensorBoard.sh
> +module load JupyterLab/3.5.0-GCCcore-11.3.0
```suggestion
```
I expect that we can safely remove jupyter lab as well

2024-11-23 18:50 UTC, saharmahdie commented on tutorial/5_profiling/TensorBoard.sh
> +module load JupyterLab/3.5.0-GCCcore-11.3.0
I have deleted it now, sorry I was implementing in the server so I forgot to change here.

2025-02-14 08:16 UTC, VRehnberg requested changes
Thanks for the work. Have some comments about some details.

2025-02-14 08:16 UTC, VRehnberg commented on tutorial/5_profiling/README.md
> +ml load HolisticTraceAnalysis/0.2.0-gfbf-2023a
```suggestion
ml HolisticTraceAnalysis/0.2.0-gfbf-2023a
```
it's functionally equivalent, but it's looks better if we use the same load command for each module.

2025-02-14 08:16 UTC, VRehnberg commented on tutorial/5_profiling/TensorBoard.sh
Do we still need this file?

2025-02-14 08:16 UTC, VRehnberg commented on tutorial/5_profiling/jobscript-pytorch.sh
> +jupyter lab --config="${CONFIG_FILE}" --ServerApp.iopub_data_rate_limit 1e10
- You've changed to use this as file for launching in the portal instead of sbatch?
- Did increasing the IOPub data rate help, I thought the error still remained when you increased it?

2025-02-14 08:16 UTC, VRehnberg commented on tutorial/5_profiling/profiling-pytorch.ipynb
> +    "    print(f\"Error: {e}\")"
If we're to have this extra check, then perhaps we also should have some helpful text about what to do about the error.

2025-02-14 08:16 UTC, VRehnberg commented on tutorial/5_profiling/profiling-pytorch.ipynb
>      "2. Try to follow the Performance Recomendation and try again with the code below"
Does HTA give a "Performance Recommendation"? Previously there was a section in TensorBoard that gave some recommendations that you could follow which was the point of the exercise. If HTA doesn't have that we might have to change this exercise to something else.

2025-02-14 08:16 UTC, VRehnberg commented on tutorial/5_profiling/profiling-pytorch.ipynb
> +   "name": "heat_env"
You were running this with a non-default kernel? Was it necessary, probably no one will see this but could be confusing if someone does see it.

2025-02-14 10:20 UTC, saharmahdie commented on tutorial/5_profiling/TensorBoard.sh
No, we do not need it, as you mentioned that is needed for sbatch jobscripts.

2025-02-14 10:22 UTC, saharmahdie commented on tutorial/5_profiling/jobscript-pytorch.sh
> +jupyter lab --config="${CONFIG_FILE}" --ServerApp.iopub_data_rate_limit 1e10
Yes, increasing the IOPub did not solve the issue, should i remove it?

2025-02-14 11:22 UTC, saharmahdie commented on tutorial/5_profiling/profiling-pytorch.ipynb
> +    "    print(f\"Error: {e}\")"
you are right. Here I was only checking if the module is loaded successfully when i used virtual env before which is not necessary now since we have the tool installed on our system.

2025-02-14 11:31 UTC, saharmahdie commented on tutorial/5_profiling/profiling-pytorch.ipynb
> +   "name": "heat_env"
Thanks for the remark, will fix that.

2025-02-14 12:18 UTC, saharmahdie commented on tutorial/5_profiling/profiling-pytorch.ipynb
>      "2. Try to follow the Performance Recomendation and try again with the code below"
HTA does not provide direct performance recommendations like TensorBoard did. HTA helps visualize and analyze traces, offering breakdowns of execution time, idle time, and kernel usage. I will change the exercise to check with HTA how the execution time and idle time can be affected under different conditions of running the module for example, by changing the batch size.

2025-02-24 13:03 UTC, merged